# Cloudflare Pages Build Configuration
#
# IMPORTANT: This file is for DOCUMENTATION ONLY and is NOT used by Cloudflare Pages.
# Cloudflare Pages configuration must be set in the Cloudflare Dashboard.
#
# This file documents the recommended build settings for reference.

build:
  command: pip install -r requirements.txt && mkdocs build
  output: site
  environment:
    PYTHON_VERSION: "3.11"

# Domain Configuration
# Primary: docs.getdango.dev
# Production branch: main
