# Cloudflare Pages Build Configuration
# This file documents the build settings for Cloudflare Pages deployment
# Configure these settings in the Cloudflare Pages dashboard

build:
  command: pip install -r requirements.txt && mkdocs build
  output: site
  environment:
    PYTHON_VERSION: "3.11"

# Domain Configuration
# Primary: docs.getdango.dev
# Production branch: main
